export const UI_TEXT = {
  common: {
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    add: 'Adicionar',
    search: 'Pesquisar',
    filter: 'Filtrar',
    loading: 'Carregando...',
    noResults: 'Nenhum resultado encontrado',
    confirm: 'Confirmar',
    close: 'Fechar',
  },
  auth: {
    login: 'Entrar',
    signup: 'Cadastrar',
    logout: 'Sair',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    forgotPassword: 'Esqueci minha senha',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
    loginTitle: 'Entrar na sua conta',
    signupTitle: 'Criar uma conta',
  },
  dashboard: {
    title: 'Dashboard',
    balance: 'Saldo',
    income: 'Receitas',
    expenses: 'Despesas',
    recentTransactions: 'Transações Recentes',
    monthlyOverview: 'Visão Mensal',
    thisMonth: 'Este Mês',
    viewAll: 'Ver Todas',
  },
  transactions: {
    title: 'Transações',
    addTransaction: 'Nova Transação',
    editTransaction: 'Editar Transação',
    type: 'Tipo',
    amount: 'Valor',
    description: 'Descrição',
    date: 'Data',
    category: 'Categoria',
    notes: 'Observações',
    income: 'Receita',
    expense: 'Despesa',
    transfer: 'Transferência',
    status: 'Status',
    pending: 'Pendente',
    completed: 'Concluída',
    canceled: 'Cancelada',
    recurring: 'Recorrente',
    tags: 'Tags',
  },
  categories: {
    title: 'Categorias',
    addCategory: 'Nova Categoria',
    editCategory: 'Editar Categoria',
    name: 'Nome',
    type: 'Tipo',
    icon: 'Ícone',
    color: 'Cor',
    incomeCategories: 'Categorias de Receita',
    expenseCategories: 'Categorias de Despesa',
  },
  calendar: {
    title: 'Calendário',
    viewYear: 'Ano',
    viewMonth: 'Mês',
    viewWeek: 'Semana',
    today: 'Hoje',
    addTransaction: 'Nova Transação',
    noTransactions: 'Sem transações',
  },
  reports: {
    title: 'Relatórios',
    spendingByCategory: 'Gastos por Categoria',
    incomeVsExpenses: 'Receitas vs Despesas',
    monthlyComparison: 'Comparação Mensal',
    period: 'Período',
    total: 'Total',
  },
  settings: {
    title: 'Configurações',
    profile: 'Perfil',
    preferences: 'Preferências',
    currency: 'Moeda',
    language: 'Idioma',
    fullName: 'Nome Completo',
    avatar: 'Avatar',
  },
}
